name: Munin Film
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22907
title: 'Magnus & Kjella'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1c15'
    - '#413f33'
    - '#7f8085'
    - '#a99f9e'
  brandStrength: 0.8125
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
