name: Munin Film
favicon: null
layout_spectrum: 0.73914
typography_spectrum: 0.39898
title: 'Magnus & Kjella'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eceee9'
    - '#5c5c61'
    - '#a38994'
    - '#fefa00'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
