name: Munin Film
favicon: null
layout_spectrum: 0.4482294477056712
typography_spectrum: 0.5252155433408916
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.24197665718384087
  lightness: 0.7350958355236799
  saturation: 0.4065656487364322
  rhythmicContrast: 0.18768334342166781
purpose: []
