name: Munin Film
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eceee9'
    - '#5c5c61'
    - '#a38994'
    - '#fefa00'
  brandStrength: 0.24197665718384087
  lightness: 0.7350958355236799
  saturation: 0.4065656487364322
  rhythmicContrast: 0.18768334342166781
purpose: []
